### PR TITLE
Hotfix warning when closing call graph

### PR DESCRIPTION
**Pull request by edisonhello**

### CODE REVIEW

**Review by Domiii — CHANGES_REQUESTED** [review]
We don't generally want to revert `async` to promises (unless we have a good reason to).

Instead, just wrap any `await X` in `try/catch`:

try {
  await X;
}
catch (err) { ... }

**Comment by MiccWan** [comment]
> We don't generally want to revert `async` to promises (unless we have a good reason to).
> 
> Can you take a look at how `reigsterCommand` (and other "error wrappers") are implemented?
> 
> Instead, just wrap any `await X` in `try/catch`:
> 
> ```js
> try {
>   // do the work with await in it
> }
> catch (err) { ... }
> ```

The problem is `handleOnDidChangedViewState` was not supposed to be a async function, `webviewPanel.visible` is a getter which checks if the view is disposed. If we use await in that function, the view might be disposed before the promise resolve, thus makes an error when trying to get `webviewPanel.visible`.

**Comment by Domiii** [comment]
@MiccWan as we discussed then :)

**Comment by MiccWan** [comment]
@Domiii fixed

**Review by MiccWan — COMMENTED** [review]
Good

**Pull request merged**
