### PR TITLE
Add info to docs about remote debugging

### PR DESCRIPTION
**Pull request by CherryDT**
As discussed in #639 

FAQ entry about remote debugging, modification of "future work" entry accordingly.

### CODE REVIEW

**Comment by Domiii** [comment]
hi @CherryDT
Sorry for the delay - had a few big things happening the past week.
I already reviewed the PR. Looks good to me.

As you can see, there are now conflicts. That was a general problem because your test `yarn docs:build` would write to the deployment folder (which has been updated since and thus is conflicting). I fixed that. If you check out the latest `master`, `yarn docs:build` will now build to a gitignore'd folder instead, and you will not conflict with deployment results anymore. Your easiest way to fix this is to `git reset` the `docs` folder (e.g. `git reset --hard -- docs`), and then pull `master`, you should be good. Apologies for the annoyance!

**Comment by Domiii** [comment]
Also, if you have any questions or want to talk about Dbux in general, feel free to reach out to me on Discord and feel free to DM me directly. We can even jump into a voice call and look at your stuff (or other Dbux stuff) together, if you want to.
We are currently in the early stages, and I want to make sure to reach out to anyone who puts in any amount of time, such as yourself :)

**Comment by CherryDT** [comment]
Did that (however I had to do `rm -rf docs; git checkout upstream/master -- docs; git commit; git merge upstream/master`). But I don't see `docs` being in `.gitignore` now either...

**Comment by Domiii** [comment]
`docs` is the built and deployed folder. I re-build it when running the `deploy` command.

However, the `build` command is now using a different folder, as you can see [here](https://github.com/Domiii/dbux/blob/master/docs_site/package.json#L10). That's why `.gitignore` did not need that change.

**Pull request merged**
